from enum import IntEnum


class SchoolType(IntEnum):
    SCHOOL = 0
    GYMNASIUM = 1
    LYCEUM = 2
    BOARDING_SCHOOL = 3
    EVENING_SCHOOL = 4
    MUSICAL_SCHOOL = 5
    SPORT_SCHOOL = 6
    ART_SCHOOL = 7
    COLLEGE = 8
    PROFESSIONAL_LYCEUM = 9
    TECHNICAL_SCHOOL = 10
    VOCATIONAL_SCHOOL = 11
    SPECIALIZED_SCHOOL = 12
    MARTIAL_ARTS_SCHOOL = 13
